# Generated by Django 3.0.6 on 2020-05-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insta_id', models.CharField(max_length=50)),
                ('profile_pic', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('submission', models.CharField(max_length=1000)),
                ('thumbnail', models.ImageField(default='default.jpg', upload_to='thumbnails')),
            ],
        ),
    ]
