# Generated by Django 3.0.6 on 2020-05-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
