# Generated by Django 3.0.6 on 2020-05-23 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_gallery_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='entry_id',
            field=models.IntegerField(default=0),
        ),
    ]
