# Generated by Django 3.0.6 on 2020-07-17 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_auto_20200526_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='entry_id',
            field=models.CharField(default='PYBS010000', max_length=15),
        ),
    ]
